### ISSUE TITLE
Code Review and General Feedback #1

### ISSUE THREAD

**Issue by WahyuS002** [EstiAsmareta/pbkk-apotek#1]
### Naming Conventions pada Laravel

Naming Conventions (Konvensi Penamaan) adalah suatu praktik penting dalam menulis kode, bertujuan untuk menjaga konsistensi dan standar dalam penulisan kode. Hal ini memudahkan kolaborasi antara developer.

Gambar di bawah ini menjelaskan apa yang dimaksud dengan naming conventions dalam penulisan kode.
![Group 5 (3)](https://github.com/EstiAsmareta/pbkk-apotek/assets/44608522/bf3815b8-1eb5-4a8d-ae20-2d6a08c23d74)

1. Naming Convention Controller
Dalam Laravel, naming convention controller yang digunakan adalah PascalCase.
![image 7 (1)](https://github.com/EstiAsmareta/pbkk-apotek/assets/44608522/83d20575-ccb7-4295-b85b-7584b87615c3)
Pada kode dibawah lebih baik menuliskan `DataObatController` daripada `dataObatController`
https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/app/Http/Controllers/DataObatController.php#L8
Setelah melakukan perubahan pada penamaan controller, pastikan juga mengubah nama rute yang terkait dari `dataObatController` menjadi `DataObatController`, seperti yang terlihat pada kode dibawah:
https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/routes/web.php#L6-L10

2. Naming Convention Model
Naming convention model dalam Laravel juga menggunakan PascalCase.
![image 8 (1)](https://github.com/EstiAsmareta/pbkk-apotek/assets/44608522/ac1290b7-c84b-4f02-8842-955ce67c5df5)
Sebagai contoh, dalam kode yang ada dibawah, penamaan model masih menggunakan camelCase, yaitu `dataObat`. Lebih baik mengubahnya menjadi PascalCase, yaitu `DataObat`.
https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/app/Models/dataObat.php#L8
Jangan lupa untuk juga mengubah nama file model dari `dataObat.php` menjadi `DataObat.php`.
<img width="243" alt="image" src="https://github.com/EstiAsmareta/pbkk-apotek/assets/44608522/2340027c-472c-4faf-980c-b417def8d2cb">

3. Naming Convention Route
Naming convention route dalam Laravel dapat menggunakan kebab-case.
![image 9 (1)](https://github.com/EstiAsmareta/pbkk-apotek/assets/44608522/8ea4d0fa-c2e2-42bf-9eca-b6d62e022284)
Pada contoh diatas penulis artikel menggunakan kebab-case dan plural untuk naming convention route-nya, untuk sekarang karena Esti menggunakan penamaan route-nya bahasa Indonesia, jadi abaikan saja untuk penulisan penamaan plural-nya.
Sebagai contoh, kode di bawah ini bisa diubah dari `/dataObat/*` menjadi `/data-obat`:
https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/routes/web.php#L6-L10
Setelah mengubah route, pastikan juga memeriksa view yang menggunakan URL atau route tersebut untuk menghindari error.

**Comment by WahyuS002** [comment]
https://github.com/EstiAsmareta/pbkk-apotek/issues/1#issue-1943617094

Sumber Naming Conventions pada Laravel : https://medium.com/@codingwithpixelfix/laravel-naming-conventions-a04451fc7648

**Comment by EstiAsmareta** [comment]
> ### Naming Conventions pada Laravel
> 
> Naming Conventions (Konvensi Penamaan) adalah suatu praktik penting dalam menulis kode, bertujuan untuk menjaga konsistensi dan standar dalam penulisan kode. Hal ini memudahkan kolaborasi antara developer.
> 
> Gambar di bawah ini menjelaskan apa yang dimaksud dengan naming conventions dalam penulisan kode. ![Group 5 (3)](https://user-images.githubusercontent.com/44608522/275306953-bf3815b8-1eb5-4a8d-ae20-2d6a08c23d74.png)
> 
>     1. Naming Convention Controller
>        Dalam Laravel, naming convention controller yang digunakan adalah PascalCase.
>        ![image 7 (1)](https://user-images.githubusercontent.com/44608522/275293721-83d20575-ccb7-4295-b85b-7584b87615c3.png)
>        Pada kode dibawah lebih baik menuliskan `DataObatController` daripada `dataObatController`
>        https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/app/Http/Controllers/DataObatController.php#L8
>        
>        Setelah melakukan perubahan pada penamaan controller, pastikan juga mengubah nama rute yang terkait dari `dataObatController` menjadi `DataObatController`, seperti yang terlihat pada kode dibawah:
>        https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/routes/web.php#L6-L10
> 
>     2. Naming Convention Model
>        Naming convention model dalam Laravel juga menggunakan PascalCase.
>        ![image 8 (1)](https://user-images.githubusercontent.com/44608522/275293822-ac1290b7-c84b-4f02-8842-955ce67c5df5.png)
>        Sebagai contoh, dalam kode yang ada dibawah, penamaan model masih menggunakan camelCase, yaitu `dataObat`. Lebih baik mengubahnya menjadi PascalCase, yaitu `DataObat`.
>        https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/app/Models/dataObat.php#L8
>        
>        Jangan lupa untuk juga mengubah nama file model dari `dataObat.php` menjadi `DataObat.php`.
> 
> 
> <img alt="image" width="243" src="https://user-images.githubusercontent.com/44608522/275293897-2340027c-472c-4faf-980c-b417def8d2cb.png">
> 
>     3. Naming Convention Route
>        Naming convention route dalam Laravel dapat menggunakan kebab-case.
>        ![image 9 (1)](https://user-images.githubusercontent.com/44608522/275293954-8ea4d0fa-c2e2-42bf-9eca-b6d62e022284.png)
>        Pada contoh diatas penulis artikel menggunakan kebab-case dan plural untuk naming convention route-nya, untuk sekarang karena Esti menggunakan penamaan route-nya bahasa Indonesia, jadi abaikan saja untuk penulisan penamaan plural-nya.
>        Sebagai contoh, kode di bawah ini bisa diubah dari `/dataObat/*` menjadi `/data-obat`:
>        https://github.com/EstiAsmareta/pbkk-apotek/blob/bd2622017b28ef05b2f2151e5273d98ee6c9134e/routes/web.php#L6-L10
>        
>        Setelah mengubah route, pastikan juga memeriksa view yang menggunakan URL atau route tersebut untuk menghindari error.

https://github.com/EstiAsmareta/pbkk-apotek/commit/ed842921357b0e242ed638270b778f7f120b09cb

**Comment by WahyuS002** [comment]
https://github.com/EstiAsmareta/pbkk-apotek/commit/ed842921357b0e242ed638270b778f7f120b09cb#commitcomment-130482348
